spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url:
#    username:
#    password:
    hikari:
      max-lifetime: 300000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

api:
  path:
    prefix: /api/user/v1

security:
  jwt:
#    secret-key:
    authentication-expires-after: 86400000
    account_activation-expires-after: 86400000
    password_reset-expires-after: 86400000

email:
  gmail:
#    username:
#    password:

frontend:
  base-url: http://localhost:4200
  reset-password-path: /auth/reset-password
  verify-account-path: /auth/verify-account
