spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url:
#    username:
#    password:
    hikari:
      max-lifetime: 300000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

api:
  path:
    prefix: /api/user/v1

security:
  jwt:
#    secret_key:
    authentication_expires_after: 86400000
    account_activation_expires_after: 86400000
    password_reset_expires_after: 86400000

email:
  gmail:
#    username:
#    password:

frontend:
  base_url: http://localhost:4200
  reset_password_path: /auth/reset-password
  verify_account_path: /auth/verify-account
